name: Delete old Releases and Workflows

on:
  workflow_dispatch:
  schedule:
    - cron: '00 22 * * 4'

permissions: write-all

jobs:
  auto_clean:
    runs-on: ubuntu-latest
    steps:
      - name: Delete old Releases and Workflows
        uses: ophub/delete-releases-workflows@main
        with:
          gh_token: ${{secrets.GITHUB_TOKEN}}
          delete_releases: true
          releases_keep_latest: 2
          delete_tags: true
          delete_workflows: true
          workflows_keep_day: 0
